[package]
name = "day11"
version = "0.1.0"
authors = ["Dave Bort <git@dbort.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rug = "1.18"
