[package]
name = "day05"
version = "0.1.0"
authors = ["Dave Bort <git@dbort.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
image = "0.23.14"
regex = "1.5.4"
